server {
  listen 8080;
  server_name localhost;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /assets/ {
    try_files $uri =404;
  }

  location = /favicon.ico { access_log off; log_not_found off; }
  location = /robots.txt  { access_log off; log_not_found off; }

  gzip on;
  gzip_types text/plain text/css application/javascript application/json application/ld+json image/svg+xml;
  gzip_proxied any;
}
