import {
  UserPlus,
  FileText,
  FolderOpen,
  Search,
  ShieldCheck,
  CheckCircle2,
  Scale,
  ClipboardCheck,
  Banknote,
} from "lucide-react";

export const PHASE_ICON_MAP: Record<string, typeof UserPlus> = {
  "user-plus": UserPlus,
  "file-text": FileText,
  "folder-open": FolderOpen,
  "search": Search,
  "shield-check": ShieldCheck,
  "check-circle": CheckCircle2,
  "scale": Scale,
  "clipboard-check": ClipboardCheck,
  "banknote": Banknote,
  "circle": CheckCircle2,
};

export interface PhaseContent {
  summary: string;
  timeline: string;
  activities: string[];
  documents: string[];
  stakeholders: string[];
  bottlenecks: string[];
}

export const PHASE_KNOWLEDGE_BASE: Record<string, PhaseContent> = {
  "Lead & Inquiry": {
    summary: "The journey begins when a potential borrower reaches out to inquire about loan options. This phase focuses on understanding the borrower's needs, conducting preliminary affordability assessments, and determining if the applicant is a good fit for the institution's loan products.",
    timeline: "1-3 business days",
    activities: [
      "Initial contact and inquiry registration",
      "Borrower qualification questions",
      "Preliminary affordability check",
      "Product recommendation based on needs",
      "Interest rate and EMI estimation",
      "Lead scoring and prioritization",
      "Assignment to loan officer",
    ],
    documents: [
      "Basic identification (verbal or preliminary)",
      "Income estimate (self-declared)",
      "Loan requirement summary",
    ],
    stakeholders: [
      "Borrower / Applicant",
      "Sales / Relationship Manager",
      "Lead Management System",
    ],
    bottlenecks: [
      "Incomplete borrower contact information",
      "Delayed follow-up leading to lead drop-off",
      "Mismatch between borrower expectations and product eligibility",
    ],
  },
  "Application Submission": {
    summary: "The borrower formally submits a loan application with all required personal, financial, and employment details. This phase involves collecting the application form, verifying basic eligibility criteria, and processing any applicable application fees.",
    timeline: "1-2 business days",
    activities: [
      "Formal application form submission",
      "Basic eligibility screening",
      "Application fee collection",
      "Data entry and validation",
      "Duplicate application check",
      "Application acknowledgement generation",
      "Initial file creation in loan management system",
    ],
    documents: [
      "Completed loan application form",
      "Passport-size photographs",
      "PAN Card copy",
      "Application fee receipt",
    ],
    stakeholders: [
      "Borrower / Applicant",
      "Loan Processing Officer",
      "Branch Manager (for approval routing)",
    ],
    bottlenecks: [
      "Incomplete or inaccurate application forms",
      "Application fee payment delays",
      "System downtime during peak hours",
    ],
  },
  "Document Collection & KYC": {
    summary: "A comprehensive phase where all required documents are collected from the borrower and Know Your Customer (KYC) verification is completed. This ensures regulatory compliance and establishes the borrower's identity, address, and financial standing.",
    timeline: "3-7 business days",
    activities: [
      "Document checklist preparation and sharing",
      "Identity verification (Aadhaar, PAN, Passport)",
      "Address proof validation",
      "Income document collection and verification",
      "Employment verification documents",
      "Bank statement collection (6-12 months)",
      "KYC compliance check against regulatory databases",
      "Document digitization and indexing",
    ],
    documents: [
      "Aadhaar Card (front and back)",
      "PAN Card",
      "Passport / Voter ID / Driving License",
      "Address proof (utility bills, rent agreement)",
      "Salary slips (last 3-6 months)",
      "Bank statements (last 6-12 months)",
      "Form 16 / ITR (last 2-3 years)",
      "Employment certificate / Appointment letter",
      "Business registration documents (for self-employed)",
    ],
    stakeholders: [
      "Borrower / Applicant",
      "Document Verification Officer",
      "KYC Compliance Team",
      "Third-party verification agencies",
    ],
    bottlenecks: [
      "Missing or expired documents",
      "Discrepancies in name/address across documents",
      "Delays in obtaining employer verification letters",
      "KYC database connectivity issues",
    ],
  },
  "Property Valuation": {
    summary: "For secured loans, this phase involves a thorough assessment of the collateral property. A certified valuer inspects the property, determines its market value, and the legal team verifies the title and ownership chain to ensure there are no encumbrances.",
    timeline: "5-10 business days",
    activities: [
      "Site inspection scheduling",
      "Physical property inspection",
      "Market value assessment",
      "Legal title verification",
      "Encumbrance certificate check",
      "Property tax verification",
      "Valuation report preparation",
      "Comparison with registered sale values in the area",
    ],
    documents: [
      "Property sale deed / Agreement to sell",
      "Previous chain of title documents",
      "Encumbrance certificate (last 13-30 years)",
      "Property tax receipts",
      "Approved building plan",
      "Completion / Occupancy certificate",
      "NOC from housing society (if applicable)",
      "Land use certificate",
    ],
    stakeholders: [
      "Certified Property Valuer",
      "Legal Counsel / Title Verification Team",
      "Property Inspector",
      "Sub-Registrar Office (for title records)",
    ],
    bottlenecks: [
      "Property located in remote areas (travel time)",
      "Unclear or disputed property titles",
      "Missing links in the chain of ownership",
      "Pending approvals or NOCs from authorities",
    ],
  },
  "Verification & Credit Appraisal": {
    summary: "A critical assessment phase where the borrower's creditworthiness is thoroughly evaluated. This includes credit bureau checks, employment and income verification, reference checks, and detailed analysis of bank statements to assess repayment capacity.",
    timeline: "3-5 business days",
    activities: [
      "CIBIL / credit bureau score retrieval",
      "Credit history analysis",
      "Employment verification (current and previous)",
      "Reference checks (personal and professional)",
      "Bank statement analysis for cash flow patterns",
      "Existing loan obligation assessment",
      "Fraud detection screening",
      "Income stability assessment",
    ],
    documents: [
      "Credit bureau report (CIBIL, Experian, etc.)",
      "Employer verification response",
      "Reference check forms (completed)",
      "Bank statement analysis report",
      "Existing loan sanction letters",
      "Loan closure certificates (for closed loans)",
    ],
    stakeholders: [
      "Credit Analyst",
      "Verification Officer (field and desk)",
      "Credit Bureau agencies",
      "Employer HR departments",
      "References provided by applicant",
    ],
    bottlenecks: [
      "Low credit score requiring additional review",
      "Employer non-responsive to verification requests",
      "Discrepancies between declared and verified income",
      "Negative references or fraud alerts",
    ],
  },
  "Underwriting & Credit Decision": {
    summary: "The underwriting team performs a comprehensive risk assessment combining all gathered information. They evaluate debt-to-income ratios, loan-to-value metrics, and present their findings to the credit committee for a final lending decision.",
    timeline: "2-5 business days",
    activities: [
      "Comprehensive risk assessment",
      "Debt-to-income (DTI) ratio calculation",
      "Loan-to-value (LTV) analysis",
      "Cash flow adequacy assessment",
      "Policy compliance verification",
      "Credit committee presentation preparation",
      "Credit committee review and decision",
      "Risk pricing and interest rate determination",
    ],
    documents: [
      "Credit appraisal memorandum (CAM)",
      "Risk assessment report",
      "Financial ratio analysis",
      "Credit committee meeting minutes",
      "Deviation memo (if any policy exceptions)",
    ],
    stakeholders: [
      "Senior Credit Analyst / Underwriter",
      "Credit Committee members",
      "Risk Management team",
      "Branch Manager / Regional Manager",
    ],
    bottlenecks: [
      "Borderline credit cases requiring escalation",
      "Credit committee scheduling delays",
      "Policy deviations needing additional approvals",
      "Incomplete appraisal documentation",
    ],
  },
  "Conditional Approval & Offer": {
    summary: "Upon successful underwriting, the institution issues a conditional approval with a formal sanction letter. This outlines the approved loan amount, interest rate, tenure, and any conditions that must be met. The borrower reviews and accepts the terms.",
    timeline: "1-3 business days",
    activities: [
      "Sanction letter generation",
      "Terms and conditions finalization",
      "Interest rate lock (if applicable)",
      "Repayment schedule preparation",
      "Conditional requirements communication",
      "Borrower acceptance workflow",
      "Offer letter signing",
      "Cooling-off period management",
    ],
    documents: [
      "Sanction / Approval letter",
      "Loan agreement draft",
      "Terms and conditions document",
      "EMI schedule / Repayment plan",
      "Rate lock confirmation (if applicable)",
      "Borrower acceptance / consent letter",
    ],
    stakeholders: [
      "Loan Processing Officer",
      "Borrower / Applicant",
      "Legal / Compliance Team",
      "Product / Pricing team",
    ],
    bottlenecks: [
      "Borrower hesitation or counter-negotiation on terms",
      "Interest rate changes during processing period",
      "Conditional requirements difficult to fulfill",
      "Delays in borrower response / acceptance",
    ],
  },
  "Security & Legal Documentation": {
    summary: "All legal documentation is prepared and executed in this phase. For secured loans, this includes mortgage deed creation, legal opinion from empanelled lawyers, stamp duty payment, and property registration with the sub-registrar's office.",
    timeline: "5-15 business days",
    activities: [
      "Mortgage deed preparation",
      "Legal opinion from empanelled advocate",
      "Stamp duty calculation and payment",
      "Document registration at sub-registrar office",
      "Security creation (hypothecation, pledge, or mortgage)",
      "CERSAI registration",
      "Insurance policy assignment",
      "Power of Attorney execution (if required)",
    ],
    documents: [
      "Mortgage deed / Hypothecation agreement",
      "Legal opinion certificate",
      "Stamp duty payment receipt",
      "Registration receipt from sub-registrar",
      "CERSAI registration certificate",
      "Insurance policy (property / life)",
      "Post-dated cheques / ECS mandate / NACH form",
      "Personal guarantee documents (if applicable)",
    ],
    stakeholders: [
      "Legal Counsel / Empanelled Advocate",
      "Sub-Registrar office",
      "Borrower / Applicant",
      "Insurance Company",
      "CERSAI (Central Registry)",
    ],
    bottlenecks: [
      "Stamp duty cost disputes",
      "Sub-registrar office appointment availability",
      "Missing original property documents",
      "Insurance policy issuance delays",
    ],
  },
  "Pre-Disbursement Checks": {
    summary: "The final verification phase before funds are released. All documents are cross-checked one last time, insurance confirmations are obtained, the borrower's account is set up for disbursement, and any pending conditions from the sanction letter are verified as fulfilled.",
    timeline: "1-3 business days",
    activities: [
      "Final document verification and checklist completion",
      "Insurance confirmation and policy linkage",
      "Borrower account setup and verification",
      "NACH / ECS mandate registration",
      "Pre-disbursement condition compliance check",
      "Final credit bureau check (re-pull if stale)",
      "Disbursement memo preparation",
      "Approval for fund release",
    ],
    documents: [
      "Completed document checklist (signed off)",
      "Insurance policy confirmation",
      "NACH / ECS mandate registration proof",
      "Disbursement authorization memo",
      "Builder / Seller account details (for home loans)",
      "Stage completion certificate (for construction loans)",
    ],
    stakeholders: [
      "Loan Processing Officer",
      "Operations / Disbursement team",
      "Insurance liaison",
      "Branch Manager (final sign-off)",
    ],
    bottlenecks: [
      "Pending insurance policy issuance",
      "NACH mandate rejection or delays",
      "Last-minute document discrepancies",
      "Builder stage completion delays (construction loans)",
    ],
  },
  "Disbursement": {
    summary: "The culmination of the loan lifecycle where approved funds are released to the borrower or designated party. The EMI repayment schedule is activated, account statements are generated, and the borrower receives a welcome kit with all relevant loan details.",
    timeline: "1-2 business days",
    activities: [
      "Fund release authorization",
      "RTGS / NEFT transfer to borrower or seller",
      "EMI schedule activation",
      "Loan account creation in core banking",
      "Welcome kit generation and dispatch",
      "First EMI date communication",
      "Post-disbursement documentation filing",
      "Borrower notification and confirmation",
    ],
    documents: [
      "Disbursement receipt / proof of transfer",
      "EMI repayment schedule",
      "Loan account statement",
      "Welcome letter with loan details",
      "Tax benefit certificate information",
      "Customer service contact information",
    ],
    stakeholders: [
      "Disbursement / Treasury team",
      "Core Banking operations",
      "Borrower / Applicant",
      "Builder / Seller (for property loans)",
      "Customer Service team",
    ],
    bottlenecks: [
      "Beneficiary account verification failures",
      "Fund transfer processing delays",
      "Core banking system downtime",
      "Incorrect account details from borrower",
    ],
  },
};

export function getPhaseIcon(iconName: string | null) {
  return PHASE_ICON_MAP[iconName || "circle"] || CheckCircle2;
}

export function getPhaseContent(phaseName: string): PhaseContent {
  return PHASE_KNOWLEDGE_BASE[phaseName] || {
    summary: "Detailed information about this phase will be available soon.",
    timeline: "Varies",
    activities: ["Phase activities are being documented"],
    documents: ["Documentation requirements pending"],
    stakeholders: ["Stakeholder mapping in progress"],
    bottlenecks: ["Analysis pending"],
  };
}
