import pg from "pg";
import { drizzle } from "drizzle-orm/node-postgres";
import { loanProductCatalog } from "@shared/schema";

const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
const db = drizzle(pool);

const products = [
  {
    name: "Home Purchase Loan",
    code: "HL-PUR-001",
    category: "home_loan",
    description: "Standard home loan for purchasing ready-to-move or under-construction residential properties. Covers flats, villas, row houses, and builder floors.",
    minAmount: "₹5,00,000",
    maxAmount: "₹10,00,00,000",
    minTenureMonths: 12,
    maxTenureMonths: 360,
    baseInterestRate: "8.40%",
    maxInterestRate: "11.50%",
    processingFeePercent: "0.50%",
    prepaymentPenalty: "Nil for floating rate",
    minCreditScore: 700,
    maxLtv: "80%",
    minIncome: "₹25,000",
    collateralRequired: true,
    insuranceRequired: true,
    requiredDocuments: ["PAN Card", "Aadhaar Card", "Salary Slips (3 months)", "Bank Statements (6 months)", "Form 16 / ITR (2 years)", "Property Documents", "Sale Agreement", "Approved Building Plan"],
    eligibilityCriteria: ["Age 21–65 years", "Minimum 2 years employment", "CIBIL score 700+", "FOIR below 50%"],
    features: ["Floating & fixed rate options", "Balance transfer facility", "Top-up loan available", "Joint application allowed", "Tax benefits under Sec 80C & 24(b)"],
    targetSegment: "Salaried & Self-employed",
    riskGrade: "AA",
    status: "active",
    icon: "home",
    color: "#3b82f6",
  },
  {
    name: "Home Construction Loan",
    code: "HL-CON-002",
    category: "home_loan",
    description: "Loan for constructing a house on land already owned by the borrower. Disbursed in stages linked to construction milestones.",
    minAmount: "₹10,00,000",
    maxAmount: "₹5,00,00,000",
    minTenureMonths: 12,
    maxTenureMonths: 300,
    baseInterestRate: "8.65%",
    maxInterestRate: "12.00%",
    processingFeePercent: "0.50%",
    prepaymentPenalty: "Nil for floating rate",
    minCreditScore: 700,
    maxLtv: "75%",
    minIncome: "₹30,000",
    collateralRequired: true,
    insuranceRequired: true,
    requiredDocuments: ["Land ownership proof", "Approved building plan", "Construction cost estimate", "PAN & Aadhaar", "Income proof (ITR / salary slips)", "Bank statements (6 months)", "NOC from local authority"],
    eligibilityCriteria: ["Age 21–65 years", "Verified land ownership", "Approved construction plan", "CIBIL 700+"],
    features: ["Stage-wise disbursement", "Pre-EMI option during construction", "12-month moratorium", "Builder flexibility", "Tax benefits available"],
    targetSegment: "Landowners, Self-employed",
    riskGrade: "A",
    status: "active",
    icon: "home",
    color: "#3b82f6",
  },
  {
    name: "Home Loan Balance Transfer",
    code: "HL-BT-003",
    category: "home_loan",
    description: "Transfer your existing home loan from another bank at lower interest rates. Includes top-up facility for additional funding.",
    minAmount: "₹10,00,000",
    maxAmount: "₹10,00,00,000",
    minTenureMonths: 12,
    maxTenureMonths: 300,
    baseInterestRate: "8.25%",
    maxInterestRate: "10.50%",
    processingFeePercent: "0.25%",
    prepaymentPenalty: "Nil",
    minCreditScore: 725,
    maxLtv: "80%",
    minIncome: "₹30,000",
    collateralRequired: true,
    insuranceRequired: false,
    requiredDocuments: ["Existing loan account statement", "Sanction letter from current bank", "Property documents", "NOC from current lender", "Income proof", "PAN & Aadhaar"],
    eligibilityCriteria: ["Minimum 12 EMIs paid on existing loan", "No defaults in last 12 months", "CIBIL 725+", "Property valuation satisfactory"],
    features: ["Lower interest rate guaranteed", "Top-up loan up to ₹50 lakh", "Zero prepayment penalty", "Seamless transfer process", "Dedicated relationship manager"],
    targetSegment: "Existing home loan borrowers",
    riskGrade: "AAA",
    status: "active",
    icon: "home",
    color: "#3b82f6",
  },
  {
    name: "Plot Purchase Loan",
    code: "HL-PLT-004",
    category: "home_loan",
    description: "Loan for purchasing residential plots in approved layouts. Construction must begin within specified timeline.",
    minAmount: "₹5,00,000",
    maxAmount: "₹3,00,00,000",
    minTenureMonths: 12,
    maxTenureMonths: 180,
    baseInterestRate: "9.00%",
    maxInterestRate: "12.50%",
    processingFeePercent: "1.00%",
    prepaymentPenalty: "2% for first 3 years",
    minCreditScore: 700,
    maxLtv: "70%",
    minIncome: "₹25,000",
    collateralRequired: true,
    insuranceRequired: false,
    requiredDocuments: ["Plot sale agreement", "Title deed / chain of documents", "Encumbrance certificate", "Approved layout plan", "PAN & Aadhaar", "Income proof"],
    eligibilityCriteria: ["Age 21–60 years", "Plot in approved layout only", "Construction within 3 years mandatory", "CIBIL 700+"],
    features: ["Composite loan option (plot + construction)", "Flexible repayment", "Tax benefits on construction phase", "Quick disbursement"],
    targetSegment: "First-time buyers, Investors",
    riskGrade: "A",
    status: "active",
    icon: "home",
    color: "#3b82f6",
  },

  {
    name: "New Car Loan",
    code: "AL-NEW-001",
    category: "auto_loan",
    description: "Financing for brand new passenger vehicles from authorized dealerships. Covers cars, SUVs, and MUVs from all major manufacturers.",
    minAmount: "₹1,00,000",
    maxAmount: "₹1,50,00,000",
    minTenureMonths: 12,
    maxTenureMonths: 84,
    baseInterestRate: "7.65%",
    maxInterestRate: "12.50%",
    processingFeePercent: "0.50%",
    prepaymentPenalty: "2% on fixed rate, Nil on floating",
    minCreditScore: 700,
    maxLtv: "90%",
    minIncome: "₹20,000",
    collateralRequired: true,
    insuranceRequired: true,
    requiredDocuments: ["PAN Card", "Aadhaar Card", "Salary slips (3 months)", "Bank statements (3 months)", "Proforma invoice from dealer", "Driving license"],
    eligibilityCriteria: ["Age 21–65 years", "Minimum 1 year employment", "CIBIL 700+", "Existing EMI obligations < 40% income"],
    features: ["Up to 90% on-road price financing", "Doorstep document pickup", "Same-day approval possible", "No guarantor required", "Flexible EMI dates"],
    targetSegment: "Salaried & Self-employed professionals",
    riskGrade: "AA",
    status: "active",
    icon: "car",
    color: "#0ea5e9",
  },
  {
    name: "Pre-Owned Car Loan",
    code: "AL-USED-002",
    category: "auto_loan",
    description: "Financing for certified pre-owned vehicles not older than 7 years. Includes valuation and condition assessment.",
    minAmount: "₹1,00,000",
    maxAmount: "₹50,00,000",
    minTenureMonths: 12,
    maxTenureMonths: 60,
    baseInterestRate: "10.50%",
    maxInterestRate: "16.00%",
    processingFeePercent: "1.50%",
    prepaymentPenalty: "4% in first year, 2% thereafter",
    minCreditScore: 675,
    maxLtv: "80%",
    minIncome: "₹15,000",
    collateralRequired: true,
    insuranceRequired: true,
    requiredDocuments: ["Vehicle RC copy", "Insurance certificate", "Seller KYC documents", "Valuation report", "PAN & Aadhaar", "Income proof"],
    eligibilityCriteria: ["Vehicle age < 7 years at loan maturity", "Certified condition assessment", "Clean title transfer", "CIBIL 675+"],
    features: ["Quick 24-hour approval", "No seller involvement needed", "Transfer assistance included", "Warranty options available"],
    targetSegment: "Budget-conscious buyers",
    riskGrade: "BBB",
    status: "active",
    icon: "car",
    color: "#0ea5e9",
  },
  {
    name: "Two-Wheeler Loan",
    code: "AL-2W-003",
    category: "auto_loan",
    description: "Affordable financing for new motorcycles, scooters, and electric two-wheelers from authorized dealers.",
    minAmount: "₹20,000",
    maxAmount: "₹5,00,000",
    minTenureMonths: 6,
    maxTenureMonths: 48,
    baseInterestRate: "9.50%",
    maxInterestRate: "18.00%",
    processingFeePercent: "2.00%",
    prepaymentPenalty: "Nil after 6 months",
    minCreditScore: 650,
    maxLtv: "95%",
    minIncome: "₹12,000",
    collateralRequired: false,
    insuranceRequired: true,
    requiredDocuments: ["PAN Card", "Aadhaar Card", "Salary slip or income proof", "Bank statement (3 months)", "Dealer quotation"],
    eligibilityCriteria: ["Age 18–60 years", "Minimum 6 months employment", "CIBIL 650+"],
    features: ["Up to 95% financing", "Minimal documentation", "1-hour approval", "EMI as low as ₹999", "EV subsidy linkage available"],
    targetSegment: "Young professionals, Students, First-time buyers",
    riskGrade: "BB",
    status: "active",
    icon: "car",
    color: "#0ea5e9",
  },

  {
    name: "Personal Loan — Salaried",
    code: "PL-SAL-001",
    category: "personal_loan",
    description: "Unsecured personal loan for salaried professionals. For weddings, travel, medical needs, home renovation, or any personal requirement.",
    minAmount: "₹50,000",
    maxAmount: "₹40,00,000",
    minTenureMonths: 12,
    maxTenureMonths: 60,
    baseInterestRate: "10.49%",
    maxInterestRate: "21.00%",
    processingFeePercent: "2.00%",
    prepaymentPenalty: "4% of outstanding in first year",
    minCreditScore: 700,
    maxLtv: null,
    minIncome: "₹25,000",
    collateralRequired: false,
    insuranceRequired: false,
    requiredDocuments: ["PAN Card", "Aadhaar Card", "Salary slips (3 months)", "Bank statements (6 months)", "Form 16"],
    eligibilityCriteria: ["Age 23–58 years", "Minimum 2 years total experience", "1 year in current organization", "CIBIL 700+"],
    features: ["100% digital process", "No collateral needed", "Disbursal within 4 hours", "Flexible EMI options", "Top-up facility available"],
    targetSegment: "Salaried professionals",
    riskGrade: "A",
    status: "active",
    icon: "wallet",
    color: "#6366f1",
  },
  {
    name: "Personal Loan — Self-Employed",
    code: "PL-SE-002",
    category: "personal_loan",
    description: "Personal loan tailored for self-employed individuals, freelancers, and business owners with flexible income documentation.",
    minAmount: "₹1,00,000",
    maxAmount: "₹25,00,000",
    minTenureMonths: 12,
    maxTenureMonths: 48,
    baseInterestRate: "13.00%",
    maxInterestRate: "24.00%",
    processingFeePercent: "2.50%",
    prepaymentPenalty: "5% of outstanding",
    minCreditScore: 680,
    maxLtv: null,
    minIncome: "₹30,000",
    collateralRequired: false,
    insuranceRequired: false,
    requiredDocuments: ["PAN Card", "Aadhaar Card", "ITR (2 years)", "P&L and Balance Sheet", "Bank statements (12 months)", "Business registration proof"],
    eligibilityCriteria: ["Age 25–60 years", "Business vintage 3+ years", "ITR filed for 2 years", "CIBIL 680+"],
    features: ["No collateral required", "Income flexibility", "GST-linked assessment", "Quick turnaround", "Overdraft conversion option"],
    targetSegment: "Self-employed, Freelancers, Consultants",
    riskGrade: "BBB",
    status: "active",
    icon: "wallet",
    color: "#6366f1",
  },
  {
    name: "Wedding Loan",
    code: "PL-WED-003",
    category: "personal_loan",
    description: "Special-purpose personal loan for wedding expenses including venue, catering, jewelry, trousseau, and honeymoon travel.",
    minAmount: "₹1,00,000",
    maxAmount: "₹50,00,000",
    minTenureMonths: 12,
    maxTenureMonths: 60,
    baseInterestRate: "11.00%",
    maxInterestRate: "18.00%",
    processingFeePercent: "1.50%",
    prepaymentPenalty: "3% in first year, Nil after",
    minCreditScore: 700,
    maxLtv: null,
    minIncome: "₹30,000",
    collateralRequired: false,
    insuranceRequired: false,
    requiredDocuments: ["PAN Card", "Aadhaar Card", "Income proof", "Bank statements (6 months)", "Wedding invitation / vendor invoices (optional)"],
    eligibilityCriteria: ["Age 23–55 years", "Stable employment", "CIBIL 700+", "Low existing debt"],
    features: ["Pre-approved offers for existing customers", "Instant digital sanction", "No end-use restriction", "Step-up EMI option", "Co-applicant benefit"],
    targetSegment: "Young professionals, Families",
    riskGrade: "A",
    status: "active",
    icon: "wallet",
    color: "#6366f1",
  },

  {
    name: "MSME Business Loan",
    code: "BL-MSME-001",
    category: "business_loan",
    description: "Collateral-free business loan for Micro, Small & Medium Enterprises under CGTMSE guarantee scheme. For working capital, expansion, or equipment.",
    minAmount: "₹1,00,000",
    maxAmount: "₹2,00,00,000",
    minTenureMonths: 12,
    maxTenureMonths: 60,
    baseInterestRate: "12.00%",
    maxInterestRate: "18.00%",
    processingFeePercent: "2.00%",
    prepaymentPenalty: "3% of outstanding",
    minCreditScore: 680,
    maxLtv: null,
    minIncome: "₹50,000",
    collateralRequired: false,
    insuranceRequired: false,
    requiredDocuments: ["Udyam Registration / MSME Certificate", "GST Registration", "ITR (2 years)", "Bank statements (12 months)", "P&L Statement", "Partnership deed / MOA (if applicable)", "PAN & Aadhaar of proprietor/directors"],
    eligibilityCriteria: ["Business vintage 3+ years", "Annual turnover ₹10 lakh+", "CIBIL 680+ (proprietor)", "GST compliance up to date"],
    features: ["CGTMSE guarantee coverage", "No collateral needed up to ₹2 Cr", "Mudra scheme eligibility", "GST-linked assessment", "Doorstep service for MSMEs"],
    targetSegment: "Micro, Small & Medium Enterprises",
    riskGrade: "BBB",
    status: "active",
    icon: "briefcase",
    color: "#f59e0b",
  },
  {
    name: "Working Capital Loan",
    code: "BL-WC-002",
    category: "business_loan",
    description: "Short-term revolving credit facility for managing day-to-day business operations, inventory, and receivable financing.",
    minAmount: "₹5,00,000",
    maxAmount: "₹5,00,00,000",
    minTenureMonths: 6,
    maxTenureMonths: 36,
    baseInterestRate: "11.50%",
    maxInterestRate: "16.00%",
    processingFeePercent: "1.50%",
    prepaymentPenalty: "Nil",
    minCreditScore: 700,
    maxLtv: null,
    minIncome: "₹1,00,000",
    collateralRequired: false,
    insuranceRequired: false,
    requiredDocuments: ["GST returns (12 months)", "Bank statements (12 months)", "Audited financials (2 years)", "Stock / debtor statements", "PAN & Aadhaar of directors"],
    eligibilityCriteria: ["Business vintage 5+ years", "Positive net worth", "Annual turnover ₹50 lakh+", "CIBIL 700+"],
    features: ["Revolving credit line", "Pay interest only on utilization", "Auto-renewal facility", "Overdraft + CC hybrid", "Digital drawdown"],
    targetSegment: "Trading, Manufacturing, Services",
    riskGrade: "A",
    status: "active",
    icon: "briefcase",
    color: "#f59e0b",
  },
  {
    name: "Equipment Finance Loan",
    code: "BL-EQP-003",
    category: "business_loan",
    description: "Asset-backed financing for purchasing industrial machinery, medical equipment, IT infrastructure, or commercial vehicles.",
    minAmount: "₹5,00,000",
    maxAmount: "₹10,00,00,000",
    minTenureMonths: 12,
    maxTenureMonths: 84,
    baseInterestRate: "9.50%",
    maxInterestRate: "14.00%",
    processingFeePercent: "1.00%",
    prepaymentPenalty: "2% of outstanding",
    minCreditScore: 700,
    maxLtv: "85%",
    minIncome: "₹75,000",
    collateralRequired: true,
    insuranceRequired: true,
    requiredDocuments: ["Equipment proforma invoice", "Vendor details", "GST Registration", "Audited financials (3 years)", "Bank statements (12 months)", "Existing asset list"],
    eligibilityCriteria: ["Business vintage 3+ years", "Positive cash flow", "Equipment from approved OEM/vendor", "CIBIL 700+"],
    features: ["Up to 85% equipment cost funded", "Hypothecation-based security", "Tax depreciation benefits", "Seasonal EMI structuring", "Vendor direct payment"],
    targetSegment: "Manufacturing, Healthcare, IT, Logistics",
    riskGrade: "AA",
    status: "active",
    icon: "briefcase",
    color: "#f59e0b",
  },

  {
    name: "Domestic Education Loan",
    code: "EL-DOM-001",
    category: "education_loan",
    description: "Education loan for pursuing graduate, post-graduate, and professional courses in premier Indian institutions (IITs, IIMs, AIIMS, NLUs, etc.).",
    minAmount: "₹1,00,000",
    maxAmount: "₹20,00,000",
    minTenureMonths: 12,
    maxTenureMonths: 180,
    baseInterestRate: "8.50%",
    maxInterestRate: "12.00%",
    processingFeePercent: "Nil",
    prepaymentPenalty: "Nil",
    minCreditScore: 650,
    maxLtv: null,
    minIncome: "₹15,000",
    collateralRequired: false,
    insuranceRequired: false,
    requiredDocuments: ["Admission letter", "Fee structure", "Mark sheets (last qualifying exam)", "Co-applicant income proof", "PAN & Aadhaar (student + parent)", "Bank statements (6 months)"],
    eligibilityCriteria: ["Indian citizen", "Admission in recognized institution", "Age 18–35 years", "Co-applicant (parent/guardian) mandatory"],
    features: ["No collateral up to ₹7.5 lakh", "Moratorium during course + 6 months", "Interest subsidy for EWS under Vidyalaxmi", "Tax benefit under Sec 80E", "100% tuition + hostel covered"],
    targetSegment: "Students, Parents",
    riskGrade: "A",
    status: "active",
    icon: "graduation-cap",
    color: "#8b5cf6",
  },
  {
    name: "Overseas Education Loan",
    code: "EL-ABR-002",
    category: "education_loan",
    description: "Comprehensive education loan for studying abroad covering tuition, living expenses, travel, and equipment. Covers US, UK, Canada, Australia, Europe.",
    minAmount: "₹10,00,000",
    maxAmount: "₹1,50,00,000",
    minTenureMonths: 36,
    maxTenureMonths: 180,
    baseInterestRate: "9.50%",
    maxInterestRate: "13.50%",
    processingFeePercent: "1.00%",
    prepaymentPenalty: "Nil",
    minCreditScore: 680,
    maxLtv: null,
    minIncome: "₹30,000",
    collateralRequired: true,
    insuranceRequired: false,
    requiredDocuments: ["I-20 / CAS Letter / Offer Letter", "Passport copy", "GRE/GMAT/IELTS score", "Fee structure from university", "Collateral documents (above ₹7.5L)", "Co-applicant income proof", "Visa approval (pre-disbursement)"],
    eligibilityCriteria: ["Admission in QS Top 500 / recognized foreign university", "Indian citizen with valid passport", "Co-applicant required", "CIBIL 680+ (co-applicant)"],
    features: ["Covers tuition + living + travel", "Forex disbursement facility", "Moratorium up to course + 12 months", "No margin for loans up to ₹7.5L", "Tax benefits under Sec 80E"],
    targetSegment: "Students pursuing foreign education",
    riskGrade: "A",
    status: "active",
    icon: "graduation-cap",
    color: "#8b5cf6",
  },
  {
    name: "Skill Development Loan",
    code: "EL-SKL-003",
    category: "education_loan",
    description: "Short-duration loan for professional certification courses, coding bootcamps, executive MBAs, and upskilling programs from recognized providers.",
    minAmount: "₹20,000",
    maxAmount: "₹5,00,000",
    minTenureMonths: 6,
    maxTenureMonths: 36,
    baseInterestRate: "10.00%",
    maxInterestRate: "15.00%",
    processingFeePercent: "1.00%",
    prepaymentPenalty: "Nil",
    minCreditScore: 650,
    maxLtv: null,
    minIncome: "₹15,000",
    collateralRequired: false,
    insuranceRequired: false,
    requiredDocuments: ["Course enrollment proof", "Institute accreditation", "PAN & Aadhaar", "Income proof", "Bank statements (3 months)"],
    eligibilityCriteria: ["Age 18–45 years", "Course from NSDC/UGC/AICTE recognized provider", "CIBIL 650+"],
    features: ["No collateral needed", "Direct payment to institute", "Flexible EMI start", "100% course fee coverage", "RBI Skill Loan scheme eligible"],
    targetSegment: "Working professionals, Career changers",
    riskGrade: "BBB",
    status: "active",
    icon: "graduation-cap",
    color: "#8b5cf6",
  },

  {
    name: "Medical Treatment Loan",
    code: "ML-TRT-001",
    category: "medical_loan",
    description: "Emergency and planned medical procedure financing including surgery, critical illness treatment, organ transplant, and prolonged hospitalization.",
    minAmount: "₹50,000",
    maxAmount: "₹50,00,000",
    minTenureMonths: 6,
    maxTenureMonths: 60,
    baseInterestRate: "10.00%",
    maxInterestRate: "16.00%",
    processingFeePercent: "1.00%",
    prepaymentPenalty: "Nil",
    minCreditScore: 650,
    maxLtv: null,
    minIncome: "₹20,000",
    collateralRequired: false,
    insuranceRequired: false,
    requiredDocuments: ["Doctor's prescription / treatment plan", "Hospital cost estimate", "PAN & Aadhaar", "Income proof", "Insurance claim status (if any)"],
    eligibilityCriteria: ["Age 21–65 years", "Treatment at NABH/JCI accredited hospital", "CIBIL 650+", "Co-applicant for amounts > ₹10L"],
    features: ["Emergency fast-track (4-hour approval)", "Direct hospital payment", "No end-use restriction on surplus", "EMI holiday for recovery period", "Insurance top-up bridge"],
    targetSegment: "Patients, Families, Medical emergencies",
    riskGrade: "BBB",
    status: "active",
    icon: "heart-pulse",
    color: "#ef4444",
  },
  {
    name: "Fertility & IVF Loan",
    code: "ML-IVF-002",
    category: "medical_loan",
    description: "Specialized financing for fertility treatments including IVF, IUI, ICSI, surrogacy support, and related diagnostic procedures.",
    minAmount: "₹1,00,000",
    maxAmount: "₹25,00,000",
    minTenureMonths: 12,
    maxTenureMonths: 48,
    baseInterestRate: "11.50%",
    maxInterestRate: "17.00%",
    processingFeePercent: "1.50%",
    prepaymentPenalty: "Nil after 6 months",
    minCreditScore: 675,
    maxLtv: null,
    minIncome: "₹25,000",
    collateralRequired: false,
    insuranceRequired: false,
    requiredDocuments: ["Fertility clinic cost estimate", "Doctor referral letter", "PAN & Aadhaar", "Income proof", "Bank statements (3 months)"],
    eligibilityCriteria: ["Age 21–50 years", "Treatment at registered fertility clinic", "CIBIL 675+"],
    features: ["Multiple cycle financing", "Confidential processing", "Direct clinic payment", "Step-up EMI option", "Partner clinic discounts"],
    targetSegment: "Couples seeking fertility treatment",
    riskGrade: "BB",
    status: "active",
    icon: "heart-pulse",
    color: "#ef4444",
  },
  {
    name: "Cosmetic & Dental Loan",
    code: "ML-COS-003",
    category: "medical_loan",
    description: "Financing for elective procedures — dental implants, orthodontics, LASIK, cosmetic surgery, dermatology, and hair restoration.",
    minAmount: "₹25,000",
    maxAmount: "₹10,00,000",
    minTenureMonths: 6,
    maxTenureMonths: 36,
    baseInterestRate: "12.00%",
    maxInterestRate: "20.00%",
    processingFeePercent: "2.00%",
    prepaymentPenalty: "2% in first year",
    minCreditScore: 700,
    maxLtv: null,
    minIncome: "₹20,000",
    collateralRequired: false,
    insuranceRequired: false,
    requiredDocuments: ["Treatment estimate from clinic", "Clinic registration", "PAN & Aadhaar", "Income proof", "Bank statements (3 months)"],
    eligibilityCriteria: ["Age 21–55 years", "Treatment at registered clinic", "CIBIL 700+"],
    features: ["0% EMI with partner clinics", "Digital approval in 2 hours", "No collateral", "Flexible tenure", "Cashback offers with partners"],
    targetSegment: "Young professionals, Urban consumers",
    riskGrade: "BB",
    status: "active",
    icon: "heart-pulse",
    color: "#ef4444",
  },

  {
    name: "Regular Gold Loan",
    code: "GL-REG-001",
    category: "gold_loan",
    description: "Instant loan against gold ornaments and coins. Industry-standard per-gram valuation with transparent process and secure vault storage.",
    minAmount: "₹10,000",
    maxAmount: "₹1,00,00,000",
    minTenureMonths: 3,
    maxTenureMonths: 36,
    baseInterestRate: "7.50%",
    maxInterestRate: "14.00%",
    processingFeePercent: "0.25%",
    prepaymentPenalty: "Nil",
    minCreditScore: null,
    maxLtv: "75%",
    minIncome: null,
    collateralRequired: true,
    insuranceRequired: true,
    requiredDocuments: ["PAN Card", "Aadhaar Card", "Gold ornaments for pledge", "Address proof"],
    eligibilityCriteria: ["Age 18–70 years", "Gold purity 18K–24K", "No income proof needed", "No CIBIL check"],
    features: ["No income proof required", "Disbursal in 30 minutes", "Bank-grade vault storage", "Part-release facility", "Bullet repayment option", "Gold insurance included"],
    targetSegment: "All segments — farmers, traders, households",
    riskGrade: "AAA",
    status: "active",
    icon: "gem",
    color: "#d97706",
  },
  {
    name: "Agricultural Gold Loan",
    code: "GL-AGRI-002",
    category: "gold_loan",
    description: "Gold loan tailored for agricultural needs — crop financing, equipment purchase, and farm development. Priority sector lending benefits.",
    minAmount: "₹10,000",
    maxAmount: "₹25,00,000",
    minTenureMonths: 3,
    maxTenureMonths: 12,
    baseInterestRate: "7.00%",
    maxInterestRate: "9.00%",
    processingFeePercent: "Nil",
    prepaymentPenalty: "Nil",
    minCreditScore: null,
    maxLtv: "75%",
    minIncome: null,
    collateralRequired: true,
    insuranceRequired: true,
    requiredDocuments: ["Aadhaar Card", "Land ownership / tenant proof", "Gold ornaments for pledge", "Kisan Credit Card (if available)"],
    eligibilityCriteria: ["Agricultural land ownership/tenancy", "Gold purity 18K+", "Age 18–70 years"],
    features: ["Subsidized interest rate", "Priority sector classification", "Crop-cycle aligned tenure", "Interest subvention benefit", "No processing fee"],
    targetSegment: "Farmers, Agricultural workers",
    riskGrade: "AA",
    status: "active",
    icon: "gem",
    color: "#d97706",
  },
  {
    name: "Gold Loan Overdraft",
    code: "GL-OD-003",
    category: "gold_loan",
    description: "Revolving credit facility against gold with interest charged only on the utilized amount. Ideal for businesses needing flexible working capital.",
    minAmount: "₹1,00,000",
    maxAmount: "₹50,00,000",
    minTenureMonths: 12,
    maxTenureMonths: 12,
    baseInterestRate: "9.00%",
    maxInterestRate: "12.00%",
    processingFeePercent: "0.50%",
    prepaymentPenalty: "Nil",
    minCreditScore: null,
    maxLtv: "75%",
    minIncome: null,
    collateralRequired: true,
    insuranceRequired: true,
    requiredDocuments: ["PAN Card", "Aadhaar Card", "Gold ornaments", "Current account statement (optional)"],
    eligibilityCriteria: ["Age 21–65 years", "Gold purity 18K+", "No income proof needed"],
    features: ["Pay interest only on utilized amount", "Revolving credit line", "Auto-renewal facility", "Digital drawdown via app", "Multiple withdrawals allowed"],
    targetSegment: "Traders, Small business owners",
    riskGrade: "AA",
    status: "active",
    icon: "gem",
    color: "#d97706",
  },

  {
    name: "LAP — Residential Property",
    code: "LAP-RES-001",
    category: "lap",
    description: "Loan against self-owned residential property — flat, villa, or independent house. For business expansion, education, medical needs, or debt consolidation.",
    minAmount: "₹10,00,000",
    maxAmount: "₹10,00,00,000",
    minTenureMonths: 36,
    maxTenureMonths: 180,
    baseInterestRate: "9.00%",
    maxInterestRate: "14.00%",
    processingFeePercent: "1.00%",
    prepaymentPenalty: "2% for fixed rate, Nil for floating",
    minCreditScore: 700,
    maxLtv: "60%",
    minIncome: "₹40,000",
    collateralRequired: true,
    insuranceRequired: true,
    requiredDocuments: ["Property title deed", "Encumbrance certificate", "Property valuation report", "PAN & Aadhaar", "Income proof (ITR/salary)", "Bank statements (12 months)", "Existing loan NOC (if any)"],
    eligibilityCriteria: ["Property free from encumbrance", "Clear title for 15+ years", "Property in city limits", "CIBIL 700+", "Age 25–65 years"],
    features: ["Lower rate than personal loan", "No end-use restriction", "Overdraft facility option", "Long tenure up to 15 years", "Top-up available"],
    targetSegment: "Business owners, Professionals, Property owners",
    riskGrade: "AA",
    status: "active",
    icon: "building-2",
    color: "#475569",
  },
  {
    name: "LAP — Commercial Property",
    code: "LAP-COM-002",
    category: "lap",
    description: "Loan against commercial property — office space, shop, warehouse, or showroom. Higher loan amounts with competitive rates for business funding.",
    minAmount: "₹25,00,000",
    maxAmount: "₹25,00,00,000",
    minTenureMonths: 36,
    maxTenureMonths: 180,
    baseInterestRate: "9.50%",
    maxInterestRate: "15.00%",
    processingFeePercent: "1.50%",
    prepaymentPenalty: "3% in first 3 years, Nil after",
    minCreditScore: 725,
    maxLtv: "55%",
    minIncome: "₹1,00,000",
    collateralRequired: true,
    insuranceRequired: true,
    requiredDocuments: ["Commercial property documents", "Lease/rental agreements", "Valuation report", "Company financials (3 years)", "GST returns", "PAN & Aadhaar of directors"],
    eligibilityCriteria: ["Commercial property with clear title", "Business vintage 5+ years", "Positive cash flow", "CIBIL 725+"],
    features: ["Higher loan amounts", "Rental income considered for eligibility", "Business-use friendly", "Balance transfer option", "Structured repayment schedules"],
    targetSegment: "Corporates, Business owners, HNIs",
    riskGrade: "A",
    status: "active",
    icon: "building-2",
    color: "#475569",
  },
  {
    name: "LAP — Industrial Property",
    code: "LAP-IND-003",
    category: "lap",
    description: "Loan against industrial land, factory premises, or manufacturing units. Specialized valuations and assessment for industrial assets.",
    minAmount: "₹50,00,000",
    maxAmount: "₹50,00,00,000",
    minTenureMonths: 36,
    maxTenureMonths: 120,
    baseInterestRate: "10.50%",
    maxInterestRate: "16.00%",
    processingFeePercent: "1.50%",
    prepaymentPenalty: "3% of outstanding",
    minCreditScore: 725,
    maxLtv: "50%",
    minIncome: "₹2,00,000",
    collateralRequired: true,
    insuranceRequired: true,
    requiredDocuments: ["Industrial land documents", "Factory license", "Pollution clearance", "Valuation report", "Company financials (3 years)", "Plant & machinery list", "Environmental compliance"],
    eligibilityCriteria: ["Industrial property with all clearances", "Business vintage 5+ years", "Annual turnover ₹2 Cr+", "CIBIL 725+"],
    features: ["High-value funding", "Specialized industrial valuation", "Capex and expansion support", "Structured repayment linked to cash flow"],
    targetSegment: "Manufacturers, Industrialists",
    riskGrade: "BBB",
    status: "active",
    icon: "building-2",
    color: "#475569",
  },

  {
    name: "Business Credit Line",
    code: "CL-BIZ-001",
    category: "credit_line",
    description: "Pre-approved revolving credit line for businesses. Draw funds as needed, repay flexibly, and redraw without reapplication.",
    minAmount: "₹1,00,000",
    maxAmount: "₹1,00,00,000",
    minTenureMonths: 12,
    maxTenureMonths: 36,
    baseInterestRate: "13.00%",
    maxInterestRate: "24.00%",
    processingFeePercent: "1.00%",
    prepaymentPenalty: "Nil",
    minCreditScore: 700,
    maxLtv: null,
    minIncome: "₹50,000",
    collateralRequired: false,
    insuranceRequired: false,
    requiredDocuments: ["GST Registration", "Bank statements (12 months)", "ITR (2 years)", "PAN & Aadhaar", "Business registration"],
    eligibilityCriteria: ["Business vintage 2+ years", "Annual turnover ₹25 lakh+", "CIBIL 700+", "Regular GST filing"],
    features: ["Interest only on utilized amount", "No collateral needed", "Auto-renewal", "Digital drawdown via app", "Flexible repayment schedule"],
    targetSegment: "SMEs, Traders, Service businesses",
    riskGrade: "BBB",
    status: "active",
    icon: "credit-card",
    color: "#ec4899",
  },
  {
    name: "Personal Overdraft Facility",
    code: "CL-POD-002",
    category: "credit_line",
    description: "Pre-approved overdraft facility linked to salary account. Instant access to funds up to approved limit with daily interest calculation.",
    minAmount: "₹25,000",
    maxAmount: "₹15,00,000",
    minTenureMonths: 12,
    maxTenureMonths: 12,
    baseInterestRate: "12.50%",
    maxInterestRate: "18.00%",
    processingFeePercent: "0.50%",
    prepaymentPenalty: "Nil",
    minCreditScore: 725,
    maxLtv: null,
    minIncome: "₹30,000",
    collateralRequired: false,
    insuranceRequired: false,
    requiredDocuments: ["Salary account statement", "PAN & Aadhaar", "Latest salary slip", "Employment ID"],
    eligibilityCriteria: ["Salary account with the bank", "Minimum 1 year relationship", "CIBIL 725+", "Net salary ₹30,000+"],
    features: ["Daily interest calculation", "No EMI — pay as you earn", "Auto-debit from salary", "Instant access via debit card/netbanking", "Annual auto-renewal"],
    targetSegment: "Premium salaried customers",
    riskGrade: "AA",
    status: "active",
    icon: "credit-card",
    color: "#ec4899",
  },
  {
    name: "Flexi Hybrid Loan",
    code: "CL-FLX-003",
    category: "credit_line",
    description: "Hybrid product combining term loan security with overdraft flexibility. Fixed principal + revolving component for maximum financial agility.",
    minAmount: "₹5,00,000",
    maxAmount: "₹50,00,000",
    minTenureMonths: 12,
    maxTenureMonths: 60,
    baseInterestRate: "11.00%",
    maxInterestRate: "16.00%",
    processingFeePercent: "1.50%",
    prepaymentPenalty: "Nil on revolving, 2% on term",
    minCreditScore: 700,
    maxLtv: null,
    minIncome: "₹50,000",
    collateralRequired: false,
    insuranceRequired: false,
    requiredDocuments: ["PAN & Aadhaar", "Income proof", "Bank statements (6 months)", "Asset declaration"],
    eligibilityCriteria: ["Age 25–58 years", "Net income ₹50,000+", "CIBIL 700+", "Existing customer preferred"],
    features: ["Part term + part revolving", "Withdraw & repay anytime", "Interest saving on prepayment", "Single EMI for term portion", "Digital management"],
    targetSegment: "HNIs, Senior professionals",
    riskGrade: "A",
    status: "active",
    icon: "credit-card",
    color: "#ec4899",
  },
];

async function seedProducts() {
  console.log("Seeding loan product catalog...");

  for (const product of products) {
    try {
      await db.insert(loanProductCatalog).values(product as any);
      console.log(`  Created: ${product.name} (${product.code})`);
    } catch (err: any) {
      if (err.message?.includes("duplicate key") || err.code === "23505") {
        console.log(`  Skipped (exists): ${product.name} (${product.code})`);
      } else {
        console.error(`  Error: ${product.name} — ${err.message}`);
      }
    }
  }

  console.log(`\nDone! Seeded ${products.length} products.`);
  await pool.end();
}

seedProducts();
